version: '3.3'

services:
  postgresql:
    image: postgres
    container_name: pseudo-hibernate
    ports:
      - "5434:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/pseudo-hibernate 777
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test_db